import os
import sys

import warnings
warnings.filterwarnings("ignore")

from dataclasses import dataclass
from typing import Optional, Protocol, Dict, List


@dataclass
class OCRResult:
    """
    Result of running a custom OCR module.

    - output_pdf_path: Optional path to a searchable PDF generated by OCR.
      If provided, this will be preferred for downstream Docling parsing.
    - page_image_paths: Optional list of per-page images produced by OCR.
      If present and no PDF is provided, the pipeline may compose a PDF.
    - metadata: Optional dictionary for arbitrary OCR metadata and diagnostics.
    """
    output_pdf_path: Optional[str] = None
    page_image_paths: Optional[List[str]] = None
    metadata: Optional[Dict] = None


class OCRModule(Protocol):
    """
    Protocol for pluggable OCR modules.
    Implementations should minimally provide `preprocess`.
    """

    def preprocess(self, input_path: str) -> OCRResult:
        """
        Perform OCR and return an OCRResult containing either a searchable PDF
        path or per-page image paths. `input_path` is typically a PDF or image file.
        """
        ...

    def cleanup(self, result: OCRResult) -> None:
        """
        Optional clean-up hook (delete temps, release resources). Implementations
        can no-op if no clean-up is required.
        """
        ...


